#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=8gb,walltime=12:00:00
#PBS -N bl.freesurfer-long

set -e
set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

mode=`jq -r .mode config.json`

if [ "$mode" == "base" ]; then
    time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
        docker://brainlife/freesurfer:7.1.1 ./base.sh
fi

if [ "$mode" == "long" ]; then
    time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt \
        docker://brainlife/freesurfer:7.1.1 ./long.sh
fi

